---

name: Build FreeCAD MacOS app bundle

on:
  workflow_dispatch:

env:
  HOMEBREW_NO_ANALYTICS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  HOMEBREW_DEVELOPER: 1

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os:
          - macos-14
          # - macos-13
          # - macos-12

    runs-on: ${{ matrix.os }}

    timeout-minutes: 1200

    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew
        id: cache-homebrew
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.set-up-homebrew.outputs.repository-path }}
          key: ${{ runner.os }}-homebrew-${{ hashFiles('**/Brewfile') }}
          restore-keys: |
            ${{ runner.os }}-homebrew-

      # - name: Install dependencies from Brewfile
      #   run: brew bundle --file=Brewfile

      # - name: Cache Homebrew Cache
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ steps.set-up-homebrew.outputs.homebrew-cache }}
      #     key: ${{ runner.os }}-homebrew-cache-${{ hashFiles('**/Brewfile') }}
      #     restore-keys: |
      #       ${{ runner.os }}-homebrew-cache-

      - name: set foos
        id: set-foos
        run: |
          echo "foo=bar" >> "$GITHUB_OUTPUT"

      - name: print foos
        id: print-foos
        env:
          foo: ${{ steps.set-foos.outputs.foo }}
        run: echo "the value of foo is $foo"

      - name: set brew prefix & cache paths
        id: set-brew-prefix-and-cache-paths
        run: |
           bp=$(brew --prefix)
           hbc="$bp/cache"
           echo "bp=\"$bp\"" >> "$GITHUB_OUTPUT"
           echo "hbc=\"$hbc\"" >> "$GITHUB_OUTPUT"

      - name: Print Brew Prefix & Cache paths
        id: print-brew-prefix-cache-paths
        env:
          bp: ${{ steps.set-brew-prefix-and-cache-paths.outputs.bp }}
          hbc: ${{ steps.set-brew-prefix-and-cache-paths.outputs.hbc }}
        run: |
          echo "the value of bp is set to $bp"
          echo "the value of hbc is set to $hbc"

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      # - name: Cache Homebrew Packages
      #   id: cache-homebrew-packages
      #   uses: actions/cache@v4
      #   env:
      #     cache-name: cache-homebrew-packages
      #   with:
      #     path: |
      #       ${{ env.BREW_PREFIX }}
      #     key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('$HOME/Brewfile') }}
      #     restore-keys: |
      #       ${{ runner.os }}-${{ env.cache-name }}-homebrew-${{ runner.os }}-
      #
      # - name: List the state of the brew packages
      #   if: ${{ steps.cache-homebrew-packages.outputs.cache-hit != 'true' }}
      #   continue-on-error: true
      #   run: brew list
      #
      # - name: List files in Homebrew Cellar
      #   run: ls -la ${{ env.BREW_PREFIX }}/Cellar
      #
      # - name: setup freecad tap
      #   id: setup-freecad-tap
      #   run: |
      #     brew tap -v freecad/freecad
      #
      # - name: install freecad deps
      #   id: install-freecad-deps
      #   run: brew install --only-dependencies --formula -v freecad/freecad/freecad

      # - name: checkout repository
      #   uses: actions/checkout@v2

      - name: debug with lhotari/action-upterm
        id: debug-workflow-run
        # uses: actions/checkout@v2
        uses: lhotari/action-upterm@v1
        if: ${{ failure() }}
        with:
          # limit ssh access to user who triggered the workflow
          limit-access-to-actor: true
          # shut down server after 10 minutes if no one connects
          wait-timeout-minutes: 10

